language: python
python:
- '3.4'
- '3.3'
- '2.7'
- '2.6'
install: pip install -r requirements_dev.txt
script: make test-standalone
notifications:
  slack:
    secure: ahOl421yKFeC7SqxcNfu4dGlssMRngzQV1TuC6LlACHv+0deRvWwHvdHc1h6hdZ/bjnmrsnF8ycsz3RiCJwP0+iu6qREaaaniSuKHrvvrYQ+anRsn0VUYnbfpaotG8ReMAGxRbOuj1Uk7jbeZw2fQoUMgP/C7ZLtZgR1/zTb4RLSq7DWcMDL5CV/97DGkrfKs2P1DWpJS2JuxgQVeJoFIuIcPsXGqKrX4UZBHwxSqCw0Uwo5NY8YP1Dekrs+pBEuuIhWHo2hgUvgBpv8T+Hpl4kYVHFYDjq5v+ABDqR2x66ppqmQgO1yvwy7f3EM+ndz0BtnaTnqXBr9yoKIMMlATeeesXHybGIZl0ABVVsxjp3a4LpT3pI+IDjPO7MRFYsbAc2EIt31f9CXTrBDJNZtjlMMpjooC1OSOx9aPbJUmSwyHUKY0J5HymaUWyli/jhIHlfcWucccFtjDPdbnfGrBANmf1FxIzd0Ep3ponvqILcFNBCLLEqkVxJegsALvvc4w37+HydOKY4oIdZiEHagyUCJBN8iTDhWxHuXOJ4GPL+45RVcLPIgqx3oAgXM3AYcPBEvkNOw9O/m8mG6oiIWxGKtn0zacepH5Y1fF0jI1OJ007uvAAOXDC4oMybB232iRRtsjUcHYCmM62J8qH+AHmil7i2B2bT1iqX21tLLq5c=
